- name: Upgrade packages and reboot if required
  hosts: [ubuntu]
  become: yes  # Run tasks with sudo
  gather_facts: yes  # Gather facts about the system

  # Update packages and upgrade any packages with newer versions
  tasks:
    - name: Upgrade packages using apt
      apt:
        update_cache: true
        update_cache_retries: 3
        update_cache_retry_max_delay: 10
        upgrade: 'yes'
      register: upgrade_result

# Checks to see if a Reboot is required
    - name: Check if 'Reboot required' message exists
      stat:
        path: /var/run/reboot-required
      register: check_reboot

  # Ends playbook if the file doesn't exist
    - meta: end_host
      when: not check_reboot.stat.exists

  # Initiate system reboot if required
    - name: Reboot if required
      ansible.builtin.reboot:
        pre_reboot_delay: 120
        post_reboot_delay: 300
        reboot_timeout: 600