- hosts: 'hl-rf-corruscant' 
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: true
        update_cache_retries: 5
        upgrade: 'yes'
      check_mode: no
    
    - name: Deny all incoming traffic
      ufw:
        rule: deny
        direction: in

    - name: Enable ufw
      ufw:
        state: reloaded
        