- hosts: localhost
  become: true
  vars:
    ansible_connection: local
  tasks:
    - name: Confirm execution
      pause:
        prompt: "This playbook will make changes to your system. Proceed (yes/no)?"

    - name: Update apt cache and perform dist-upgrade
      apt:
        update_cache: true
        update_cache_retries: 5
        upgrade: 'dist'
      check_mode: no

    - name: Wait for automatic updates to finish
      shell: |
        timeout 300 bash -c '
        while lsof /var/lib/dpkg/lock-frontend; do 
          sleep 2; 
        done'
      become: true
      changed_when: false

    - name: Install essential packages
      apt:
        name: ['zsh', 'htop', 'git', 'curl', 'vim', 'nmap', 'net-tools', 'tcpdump', 'python3-pip', 'python3-venv', 'build-essential', 'libssl-dev', 'docker.io', 'nodejs', 'npm', 'tmux']
        state: present

    - name: Add user to docker group
      user:
        name: ridgfam
        groups: docker
        append: yes

    - name: Set up sudoers to allow no password for user
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: '^ridgfam ALL=\(ALL\) NOPASSWD: ALL'
        line: "ridgfam ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'
      become: true
      check_mode: no

    - name: Check if .zshrc exists
      stat:
        path: /home/ridgfam/.zshrc
      register: zshrc_stat

    - name: Backup .zshrc if it exists
      copy:
        src: /home/ridgfam/.zshrc
        dest: /home/ridgfam/.zshrc.bak
        remote_src: yes
      when: zshrc_stat.stat.exists

    - name: Install Oh-My-Zsh
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        users:
          - username: ridgfam

    - name: Set file permissions for .zshrc
      file:
        path: /home/ridgfam/.zshrc
        mode: '0644'
        owner: ridgfam
        group: ridgfam

    - name: Set ZSH_THEME
      lineinfile:
        path: /home/ridgfam/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="agnoster"'
        owner: ridgfam
        group: ridgfam

    - name: Set plugins
      lineinfile:
        path: /home/ridgfam/.zshrc
        regexp: '^plugins='
        line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting history kubectl docker vscode)'
        owner: ridgfam
        group: ridgfam

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/ridgfam/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/ridgfam/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes

    - name: Install zsh-kubectl-prompt
      git:
        repo: https://github.com/superbrothers/zsh-kubectl-prompt.git
        dest: /home/ridgfam/.oh-my-zsh/custom/plugins/kubectl
        clone: yes
        update: yes

    - name: Test .zshrc for errors
      shell: zsh -n /home/ridgfam/.zshrc
      become: true
      become_user: ridgfam

    - name: Log failure notification
      copy:
        dest: /home/ridgfam/ansible_failure.log
        content: "The playbook failed. Please check the system."

  handlers:
    - name: Source .zshrc
      shell: source /home/ridgfam/.zshrc
      args:
        executable: /bin/zsh
      become: true
      become_user: ridgfam
