# This playbook sets up the Zabbix agent 2 on the specified host.
# It performs the following tasks:
# 1. Downloads the Zabbix release package from the specified URL and saves it to '/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb'.
# 2. Installs the Zabbix release package using the 'apt' module.
# 3. Updates the apt cache using the 'apt' module.
# 4. Installs the Zabbix agent 2 and its plugins using the 'apt' module.
# 5. Enables and starts the Zabbix agent 2 service using the 'systemd' module.

- hosts: '<specify host>'
  become: yes
  tasks:
    - name: Download Zabbix release
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Install Zabbix release
      apt:
        deb: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix agent 2 and plugins
      apt:
        name:
          - zabbix-agent2
          - zabbix-agent2-plugin-*
        state: present

    - name: Enable and start Zabbix agent service
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes