
- hosts: 'hl-rf-corruscant'
  become: yes
  tasks:
    - name: Import Zabbix public key
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Add Zabbix repository
      apt_repository:
        repo: deb https://repo.zabbix.com/zabbix/6.0/ubuntu $(lsb_release -sc) main
        state: present
        update_cache: yes

    - name: Install Zabbix agent 2
      apt:
        name: zabbix-agent2
        state: present

    - name: Copy Zabbix agent configuration file
      copy:
        src: /path/to/your/zabbix_agentd2.conf
        dest: /etc/zabbix/zabbix_agentd2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start Zabbix agent service
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: started