---
 - hosts: all
   tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/zsh-users/zsh-autosuggestions
       dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
       clone: yes
       update: yes